### ISSUE TITLE
Issue: Cannot copy default decks anymore

### ISSUE THREAD

**Issue by ObsidianTTRPGProject** [alexkurowski/solo-toolkit#11]
Something has changed and its no longer possible to click to copy the default Tarot or Standard deck.

**Comment by alexkurowski** [comment]
Good catch! Should be fixed in version 0.3.24. Unfortunately for now it's only possible to copy-paste default cards if you set "Card click behavior" option to "Image" (but it'll create "Pasted image" files). I still haven't fully figured out how to best handle this feature, but I'm working on it

**Comment by ObsidianTTRPGProject** [comment]
Love your work mate :)
